# Add your monitor interface
source=wlan0:name=wlan0mon

# Enable wireless IDS alerts
alert=DEAUTHFLOOD,rate=10/s,burst=20
alert=DISASSOCFLOOD,rate=10/s,burst=20
alert=APCRYPTCHANGE
alert=SSIDPROBEDIFF
