# Interface and Driver
interface=wlan0
driver=nl80211

# Wi-Fi Configuration
ssid=Nana_
channel=11
hw_mode=g

# Wireless Capabilities & Standards
ieee80211n=1
wmm_enabled=1

# Access Control 
auth_algs=1
ignore_broadcast_ssid=0
